### ISSUE TITLE
Add a new database

### ISSUE THREAD

**Issue by nonmadden** [TeamSQL/desktop-app#142] opened 2017-08-02 11:27 UTC
Can't add a new database right now?

**Comment by erenbaydemir** [comment] 2017-08-03 13:59
TeamSQL doesn't have visual tools to manage db structure since it's focused on running queries. But it becomes impossible to connect and work to servers without and databases since it won't be possible to create a query window without a database. We're are aware of the issue and this will be fixed in the next releases. Thank you!

**Comment by nonmadden** [comment] 2017-08-04 00:46
Thank you bro!

**Closed** 2018-04-06 11:24 UTC
Labels: feature-request

**Comment by Ciwan1859** [comment] 2018-05-28 12:04
I still cannot create a database in TeamSQL, or at least it isn't intuitive. Is this by design?

**Comment by L-oris** [comment] 2018-07-15 08:00
@Ciwan1859 for now, as a workaround, you can just do it from a new tab
It doesn't matter if you are doing it from another DB

```sql
CREATE DATABASE my_database;
```

Then, for a table
```sql
CREATE TABLE amigos(
    id INT NOT NULL,
    name VARCHAR(45) NULL,
    PRIMARY KEY(id)
);
```

Anyway, I think TeamSQL is a really nice tool overall, and having `create DB` `drop DB` and `create table` buttons would make it even better 👍

**Comment by turboc1208** [comment] 2019-02-12 03:50
any progress on database object editing within the application?  Just doing it via the command is just a work around.  It would be much better to have a grid based method for creating tables, views, etc
