### ISSUE TITLE
Signup / Signin errors should be more descriptive when there is a connection issue. 

### ISSUE THREAD

**Issue by erenbaydemir** [TeamSQL/desktop-app#69] opened 2017-04-04 08:06 UTC
If the client cannot access to API due to a firewall configuration. users cannot sign in or sign out but don't see any error messages about connectivity issues. This creates a confusion and users think that their email addresses are in use.

**Comment by abacigil** [comment] 2017-04-11 11:05
Duplicate of https://github.com/TeamSQL/desktop-app/issues/69

**Closed by abacigil** 2017-04-11 11:05 UTC
Labels: bug, duplicate, ui
