### ISSUE TITLE
feature to enable SSL

### ISSUE THREAD

**Issue by akinuk80** [TeamSQL/desktop-app#78] opened 2017-04-11 06:28 UTC
OS: Linux x64 4.4.0-72-generic
VERSION: 0.9.84
---------------
Database Type: PostgreSQL
How can this issue be reproduced?
I am trying to connect to PostgreSQL for which I need SSL "require" to be enabled that does not exist due to which I am unable to make a connection.

**Comment by abacigil** [comment] 2017-04-11 07:33
Duplicate of https://github.com/TeamSQL/desktop-app/issues/47

**Closed by abacigil** 2017-04-11 07:33 UTC
Labels: duplicate

**Comment by abacigil** [comment] 2017-04-12 20:49
It's available with v0.9.86, we've just released it, please update.

**Comment by akinuk80** [comment] 2017-04-13 23:39
Thank you, SSL is enabled that led me to access the database.
