### ISSUE TITLE
Manually changed column width should be retained after re-executing query. 

### ISSUE THREAD

**Issue by erenbaydemir** [TeamSQL/desktop-app#65] opened 2017-04-01 05:39 UTC
If a user changes the width of a column in the results data grid, we should retain the width so user won't need to change the width repeatedly after each query execution.

**Comment by abacigil** [comment] 2017-04-11 11:09
Duplicate of https://github.com/TeamSQL/desktop-app/issues/44

**Closed** 2018-03-30 08:26 UTC
Labels: duplicate, feature-request, ui
