### ISSUE TITLE
Fixed Columns Width

### ISSUE THREAD

**Issue by OrkanCom** [TeamSQL/desktop-app#88] opened 2017-04-18 06:04 UTC
OS: Windows_NT x64 6.3.9600
VERSION: 0.9.87
---------------
Database Type: MS Sql
How can this issue be reproduced?

_This could be bug or feature request. I don't know, you decide._
_I'm using Microsoft Windows 8.1 64x with all updates installed._

I fixed length of Columns to see the data in it. But when I run the query again, TeamSQL changes columns width to smaller ones. So I think it's not a good way to work more efficient. It could be better if TeamSQL remember the columns widths if current user has been changed them. Please look at screenshots, you will get the idea.

![columns width fixed](https://cloud.githubusercontent.com/assets/13241853/25116510/e509478e-2415-11e7-9a68-be8a66f4b652.png)
![columns width back to smaller](https://cloud.githubusercontent.com/assets/13241853/25116512/eae0bb38-2415-11e7-98ad-8c627d4afcd9.png)

**Comment by abacigil** [comment] 2017-04-18 06:28
Hi @OrkanCom ,

Duplicate of https://github.com/TeamSQL/desktop-app/issues/65

**Closed by abacigil** 2017-04-18 06:28 UTC
