### ISSUE TITLE
Edit on grid directly

### ISSUE THREAD

**Issue by tbatur** [TeamSQL/desktop-app#79] opened 2017-04-11 06:29 UTC
When I open a table result (without join), I want to edit columns on grid directly and teamsql can update that row its with primary key.

**Comment by abacigil** [comment] 2017-04-11 11:22
Duplicate of https://github.com/TeamSQL/desktop-app/issues/71

**Closed** 2017-04-11 11:22 UTC
Labels: duplicate

**Comment by abacigil** [comment] 2018-03-26 12:34
Please update to 3.2.187 version, inline editing feature is now available.

Thanks,
