### ISSUE TITLE
Option to store column width per table

### ISSUE THREAD

**Issue by mpmlj** [TeamSQL/desktop-app#44] opened 2017-03-21 22:13 UTC
Hi,

Currently all columns in query results have equal widths, however I would like to see more content for text fields, for example, but shrink bool fields to their minimum, etc.

It would be great to have an option to store field sizes per table. Currently, after each refresh, column widths are reset.

Thanks!

P.S.
GREAT WORK, guys! Thrilled to see your progress. Good luck!

**Comment by abacigil** [comment] 2017-04-18 06:30
Duplicate of https://github.com/TeamSQL/desktop-app/issues/65

**Closed by abacigil** 2017-04-18 06:30 UTC
