### ISSUE TITLE
Declared Variables not working

### ISSUE THREAD

**Issue by bmrankin** [TeamSQL/desktop-app#265] opened 2018-05-11 16:18 UTC
OS: Darwin x64 17.5.0
VERSION: 3.3.203
---------------

Error is: Must declare the scalar variable "@ERP_Customer_No".
Also on @Account_No and @Start_Date

Query was running previously and currently can run in SQL Server Management Studio.

Any ideas?

Thanks

Database Type: SQL Server 2012r2

How can this issue be reproduced?

```
declare @ERP_Customer_No nvarchar(20)
declare @Account_No nvarchar(50)
declare @Start_Date date -- YYYY-MM-DD

----------------------------
------- ENTER INFO ---------
set @ERP_Customer_No = 'C0055555'
set @Account_No = '55555'
set @Start_Date = '2018-05-01'  -- YYYY-MM-DD
----------------------------
----------------------------

-- DO NOT EDIT BELOW HERE --
----------------------------
----------------------------
insert into customers
select 
    [No_]
    ,''
    ,[Name]
    ,[Address]
    ,[Address 2]
    ,[City]
    ,[County]
    ,[Post Code]
    ,[Phone No_]
    ,[Bill-to Customer No_]
    ,@Start_Date
    ,''
    ,''
    ,'True'
    ,'TRUE'
from [ERP$Customer]
where [No_] = @ERP_Customer_No

update customers
    set no = @Account_No
where erp_customer_no = @ERP_Customer_No


select * from customers
where erp_customer_no = @ERP_Customer_No
```

**Comment by BrianWBrown** [comment] 2018-06-03 11:59
I'm having the same issue.

**Comment by udayse** [comment] 2018-06-12 01:36
Having the same issue with MSSQL. What changed to cause this? All these queries used to work before.

**Comment by GreenHedgehog** [comment] 2018-07-25 05:22
Having the same issue, but i found some kind of solution - just wrap query in begin/end like this: 
```
begin
    declare @r bigint = 4823800869
    declare @brv binary(8)
    set @brv = cast(@r as binary(8))

    EXECUTE [Export].[Get_Subject_rv] @rv = @brv;
end
```
Maybe it would helpful for someone.

**Comment by otrabalhador** [comment] 2018-07-26 01:15
@GreenHedgehog, this helped me. Thanks!

**Comment by otrabalhador** [comment] 2018-07-26 12:01
It looks like the problem is that TeamSQL executes each line separately as individual batches of execution. In TSQL (or MSSQL), the DECLARE variables are temporary only to the execution batch. That explains why the variable is not found when it is used later in the query, after its DECLARATION.

IMHO, a fix for this would be to face the whole query as one execution batch in TSQL, since you're not supporting GO statements yet.

PS: TSQL is Transact-SQL, not TeamSQL

**Comment by murteza** [comment] 2018-08-28 11:51
Hi @bmrankin , @BrianWBrown , @udayse , @GreenHedgehog , @otrabalhador 

Thanks for reaching out to us. There is a bug which we will fix in [TeamSQL 4 Beta](https://teamsql.io/nightly). Please stay tuned!

**Closed** 2018-08-31 08:26 UTC
Labels: bug
